### ISSUE TITLE
commit will always suceed

### ISSUE THREAD

**Issue by dnlopes** [AgilData/tpcc#2]
Hi,
with your current implementation transaction will always "suceed". At "TpccStatements.java" you have a commit method that catch the SQL Exception. You call this method to commit transaction at "Delivery.java", "NewOrder.java", etc.

However, since you catch the SQL exception inside the commit method, you will always "return 1" at the end of a transaction.

Solution: do not catch SQL exception in "commit" method in "TpccStatements.java" and add the throws signature. This way, you will "return 0/1" properly.

Thanks,
David

**Comment by andygrove** [comment]
Thanks. This is now fixed.
