### ISSUE TITLE
resultset bug

### ISSUE THREAD

**Issue by bucketli** [AgilData/tpcc#5]
in NewOrders.neworder

...
ResultSet rs0 = pstmt35.executeQuery();
                    // ResultSet rs1 = pstmt35.executeQuery();
                    if (rs0.next()) {
                        c_discount = rs0.getFloat(1);
                        c_last = rs0.getString(2);
                        c_credit = rs0.getString(3);
                        // }
                        // if (rs1.next()) {
                        // w_tax = rs1.getFloat(1);
                        w_tax = rs0.getFloat(1);
                    }
                    rs0.close();
                    // rs1.close();

```
                should merge rs0 and rs1,or jdbc will throw exception
```

...

**Comment by andygrove** [comment]
Thanks. This is now fixed.
